/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package entrega_introducao;

import java.util.ArrayList;
import org.apache.commons.collections4.CollectionUtils;
import java.util.List;

public class App{
	public static void main (String[] args){}
		public boolean verificaListaVazia(List<String> lista){
			return CollectionUtils.isEmpty(lista);
	}
}
