/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package entrega_introducao;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;


public class LibTest {
    @Test public void testeTrue() {
	App a = new App();
	List<String> lista = new ArrayList<>();
        assertEquals(true, a.verificaListaVazia(lista));
    }

    @Test public void testeFalse() {
	App a = new App();
        List<String> lista = new ArrayList<>();
	lista.add("Hello World");
	lista.add("Yasmin");
        assertEquals(false, a.verificaListaVazia(lista));
    }
}

