/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package teste_api_aluguel;

import java.util.Scanner;

import org.apache.http.HttpEntity;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.utils.URIBuilder;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.util.EntityUtils;
import org.json.JSONObject;

public class AppYAA {
	public static void main(String[] args) {
		System.out.println("Yasmin de Araújo Arantes");
		System.out.println("Esta aplicação está consumindo uma API Web (aluguebug.herokuapp.com/calc)");
		
		Scanner input = new Scanner(System.in);
		System.out.println("\nDigite o valor nominal: ");
		double valorNominal = input.nextDouble();
		System.out.println("\nDigite o dia: ");
		int dia = input.nextInt();
		
		entradaDoUsuario(valorNominal, dia);
		
		input.close();
	}
	
	public static double entradaDoUsuario(double valor_nominal, int dia) {
		
		Aluguel aluguel = new Aluguel(valor_nominal, dia);
		JSONObject json = new JSONObject(aluguel);
		String stringJSON = json.toString();

		CloseableHttpClient httpClient = HttpClients.createDefault();
		try {
			URIBuilder builder = new URIBuilder("https://aluguebug.herokuapp.com/calc");
			builder.setParameter("dados", stringJSON);
			HttpGet request = new HttpGet(builder.build());
			CloseableHttpResponse response = httpClient.execute(request);
			HttpEntity entity = response.getEntity();
			if (entity != null) {
				String result = EntityUtils.toString(entity);
				System.out.println(result);
				result = result.replace("\\","");
				result = result.replace("\"{","{");
				JSONObject obj =  new JSONObject (result);
				return (double) obj.get("valor_calculado");
			}
		} catch (Exception e) {
			// TODO: handle exception
		}
		return -1;
	}


}
